FROM debian:11

WORKDIR /root

RUN apt-get update && \
    apt-get install -y wget apt-transport-https gnupg2 curl apache2 php libapache2-mod-php php-mysql php php-apcu php-cli php-common php-curl php-gd php-imap php-ldap php-mysql php-xmlrpc php-xml php-mbstring php-bcmath php-intl php-zip php-redis php-bz2 libapache2-mod-php php-soap php-cas

COPY glpi-10.0.17.tgz glpi-10.0.17.tgz
RUN tar -xvf glpi-10.0.17.tgz || mv glpì /var/www/