from debian:11

WORKDIR /root

RUN apt-get update && \
    apt-get install -y wget apt-transport-https gnupg2 curl apache2 php libapache2-mod-php php-mysql php php-{apcu,cli,common,curl,gd,imap,ldap,mysql,xmlrpc,xml,mbstring,bcmath,intl,zip,redis,bz2} libapache2-mod-php php-soap php-cas