services:
  cadvisor:
    image: ${IMAGE_CADVISOR}
    container_name: ${CONTAINER_NAME_CADVISOR}
    #platform: linux/aarch64
    ports:
      - "${APP_PORT_INTERNAL_CADVISOR}:8080"
    restart: always
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/mnt/docker_data/docker:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    privileged: true

  prometheus:
    image: ${IMAGE_PROMETHEUS}
    container_name: ${CONTAINER_NAME_PROMETHEUS}
    restart: always
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    privileged: true
    depends_on:
      - cadvisor

  grafana:
    image: ${IMAGE_GRAFANA}
    container_name: ${CONTAINER_NAME_GRAFANA}
    network_mode: host
    ports:
      - "${APP_PORT_INTERNAL_GRAFANA}:3000"
    restart: always
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    privileged: true
    volumes: 
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
    depends_on:
      - prometheus
#
#volumes:
#  grafana-data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${DEVICE_VOLUME}
